function outData = importReport_mar23(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  UNTITLED = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile1("\\fs-56-ah\vmgr$\home06\clapierr\Documents\Demo\CovidVis\csse_covid_19_data\csse_covid_19_daily_reports\03-29-2020.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Mar-2020 23:52:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FIPS", "Admin2", "Province_State", "Country_Region", "Last_Update", "Lat", "Lon", "Confirmed", "Deaths", "Recovered", "Active", "Combined_Key"];
opts.VariableTypes = ["double", "categorical", "categorical", "categorical", "datetime", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Combined_Key", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Admin2", "Province_State", "Country_Region", "Combined_Key"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Last_Update", "InputFormat", "M/d/yy HH:mm");

% Import the data
outData = readtable(filename, opts);

end